version: '3.8'

services:
  mysql:
    image: mysql:latest
    networks:
      - settlement_network
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  spring-boot-app:
    image: settlement-system:1.0
    networks:
      - settlement_network
    container_name: spring-boot-container
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy

networks:
  settlement_network:
    driver: bridge